server:
  port: 8085
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: id
            client-secret: secret
            scope:
                  - email
                  - profile
                  - email
                  - address
                  - phone

            authorization-grant-type: authorization_code
            client-name: Google
        provider:
            google:
                authorization-uri: https://accounts.google.com/o/oauth2/auth
                token-uri: https://accounts.google.com/o/oauth2/token
                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                user-name-attribute: sub
                jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
                issuer-uri: https://accounts.google.com


              #scope: hace que el usuario de google nos de permisos para acceder a su perfil
              #- email
              #- profile